# Generated by Django 4.1.7 on 2023-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230307_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('agent', 'Agent'), ('admin', 'Admin')], default='regular', max_length=50),
        ),
    ]
